### ISSUE TITLE
477 "Signed Request Expected"

### ISSUE THREAD

**Issue by wetterfroschdus** [nborrmann/jodel_api#11]
"Please open an issue"

**Comment by nborrmann** [comment]
fixed.

**Comment by wetterfroschdus** [comment]
mhm, still getting 477, uninstalled my version from pip and cloned from github, same result.

**Comment by nborrmann** [comment]
Tests are passing though.

But you're right, I didn't bump the version, so it wasn't published to PyPi. I did that now, travis will deploy after running the tests.

On which requests do you get the error? Make sure you are on version 1.1.1. (Run `pip freeze` to get the version).

**Comment by wetterfroschdus** [comment]
Ok, yeah, everything works now.
i had the old version installed for python 3.
and i was using python 3.
